export interface CreateOrUpdateCourtInput {
  id: number;
  creationTime: Date;
  creatorUserId: number;
  lastModificationTime: Date;
  lastModifierUserId: number;
  courtCode: string;
  courtDescription: string;
  courtNumber: string;
  courtReader: string;
  courtReaderNumber: string;
  courtReaderEmail: string;
  courtAhlmed: string;
  courtAhlmedNumber: string;
  courtAhlmedEmail: string;
  forumForumName: string;
  forumId: number |string| null;
  forumCategoryForumCategoryName: string;
  forumCatId: number |string| null;
  provinceProvinceName: string;
  provinceId: string | null;
  divisionDivisionName: string;
  divisionId: number |string| null;
  cityCityName: string;
  cityId: number |string| null;
  tehsilTehsilName: string;
  tehsilId: number |string| null;
  branchBranchName: string;
  branchId: number |string| null;
}
