export default class Stores {
  static AuthenticationStore: string = 'authenticationStore';
  static RoleStore: string = 'roleStore';
  static TenantStore: string = 'tenantStore';
  static UserStore: string = 'userStore';
  static ForumStore: string = 'forumStore';
  static CaseTypeStore: string = 'caseTypeStore';
  static LitigantTypeStore: string = 'litigantTypeStore';
  static DesignationStore: string = 'designationStore';
  static BranchStore: string = 'branchStore';
  static FirmStore: string = 'firmStore';
  static CourtStore: string = 'courtStore';
  static CityStore: string = 'cityStore';
  static LawyerStore: string = 'lawyerStore';
  static ClientStore: string = 'clientStore';
  static BenchStore: string = 'benchStore';
  static TehsilStore: string = 'tehsilStore';
  static PackageStore: string = 'packageStore';
  static CaseRegistrationStore: string = 'caseRegistrationStore';
  static DivisionStore: string = 'divisionStore';
  static CaseProceedingStore: string = 'caseProceedingStore';
  static ProvinceStore: string = 'provinceStore';
  static PresidingOfficerStore: string = 'presidingOfficerStore';
  static ForumCategoryStore: string = 'forumCategoryStore';
  static SessionStore: string = 'sessionStore';
  static AccountStore: string = 'accountStore';
}
